# Generated by Django 5.2.17 on 2026-10-02 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_manager_sections(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    ManagerScope = apps.get_model("accounts", "ManagerScope")
    for user in User.objects.filter(is_system_admin=True, is_superuser=False):
        values = user.hr_copilot_sections or []
        for raw_value in values:
            value = str(raw_value).strip().upper()
            if value:
                ManagerScope.objects.get_or_create(
                    manager_id=user.pk,
                    scope_type="SECTION",
                    value=value,
                    defaults={"is_active": True},
                )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_hr_copilot_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('SECTION', 'Section'), ('DEPARTMENT', 'Department')], max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scope_type', 'value', 'id'),
                'constraints': [models.UniqueConstraint(fields=('manager', 'scope_type', 'value'), name='unique_manager_scope_value')],
            },
        ),
        migrations.RunPython(backfill_legacy_manager_sections, migrations.RunPython.noop),
    ]
