# Generated by Django 5.2.17 on 2026-09-28 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_copilot', '0003_add_pending_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copilotconversationcontext',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveConstraint(
            model_name='copilotconversationcontext',
            name='hr_copilot_user_conversation',
        ),
        migrations.RenameIndex(
            model_name='copilotactionaudit',
            new_name='hr_copilot__user_id_a46417_idx',
            old_name='hr_copilot_action_audit_user_id_c36a99_idx',
        ),
        migrations.RenameIndex(
            model_name='copilotactionaudit',
            new_name='hr_copilot__action__c184dc_idx',
            old_name='hr_copilot_action_audit_action__6c00c4_idx',
        ),
        migrations.RenameIndex(
            model_name='copilotactionaudit',
            new_name='hr_copilot__session_3602b4_idx',
            old_name='hr_copilot_action_audit_session_7026f0_idx',
        ),
        migrations.RenameIndex(
            model_name='copilotpendingaction',
            new_name='hr_copilot__user_id_a711a7_idx',
            old_name='hr_copilot_pending_action_user_id_c24b4e_idx',
        ),
        migrations.RenameIndex(
            model_name='copilotpendingaction',
            new_name='hr_copilot__status_e4726f_idx',
            old_name='hr_copilot_pending_action_status_67a1f8_idx',
        ),
        migrations.RenameIndex(
            model_name='copilotpendingaction',
            new_name='hr_copilot__convers_53a1f7_idx',
            old_name='hr_copilot_pending_action_convers_930db0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='copilotconversationcontext',
            unique_together={('user', 'conversation_id')},
        ),
    ]
