# Generated by Django 5.2.6 on 2026-09-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_copilot", "0004_alter_copilotconversationcontext_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="copilotactionaudit",
            name="explicit_confirmation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="copilotconversationcontext",
            name="messages",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="copilotpendingaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("AWAITING_INFORMATION", "Awaiting Information"),
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved - Executing"),
                    ("EXECUTED", "Successfully Executed"),
                    ("CANCELLED", "Cancelled by User"),
                    ("EXPIRED", "Expired (Timeout)"),
                    ("FAILED", "Execution Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
