from django.urls import path
from .views import (
    AdminAttendanceView,
    AdminDashboardView,
    AttendanceHistoryView,
    TodayAttendanceView,
    CheckInView,
    CheckOutView,
    AdminForceCheckoutView,
    KioskFaceCheckInView,
    KioskFaceCheckOutView,
    FaceVerifyView,
    WebsiteFacialCheckInView,
    WebsiteFacialCheckOutView,
    MyTeamView,
    ShiftListView,
    EmployeeShiftSelfAssignView,
    AdminEmployeeShiftAssignView,
    AdminEmployeeShiftBulkAssignView,
    AdminShiftConfigurationView,
    AdminAllShiftsView,
    MyShiftView,
)


urlpatterns = [
    path("check-in/", CheckInView.as_view(), name="check-in"),
    path("website-facial-check-in/", WebsiteFacialCheckInView.as_view(), name="website-facial-check-in"),
    path("website-facial-check-out/", WebsiteFacialCheckOutView.as_view(), name="website-facial-check-out"),
    path("check-out/", CheckOutView.as_view(), name="check-out"),
    path("today/", TodayAttendanceView.as_view(), name="today-attendance"),
    path("history/", AttendanceHistoryView.as_view(), name="attendance-history"),
    path("kiosk/check-in/", KioskFaceCheckInView.as_view(), name="kiosk-check-in"),
    path("kiosk/check-out/", KioskFaceCheckOutView.as_view(), name="kiosk-check-out"),
    path("verify-face/", FaceVerifyView.as_view(), name="verify-face"),
    path("my-team/", MyTeamView.as_view(), name="my-team"),
    # Shift assignment endpoints
    path("shifts/", ShiftListView.as_view(), name="shift-list"),
    path("my-shift/", MyShiftView.as_view(), name="my-shift"),
    path("my-shift/assign/", EmployeeShiftSelfAssignView.as_view(), name="self-assign-shift"),
    path("admin/shift/assign/", AdminEmployeeShiftAssignView.as_view(), name="admin-assign-shift"),
    path("admin/shift/bulk-assign/", AdminEmployeeShiftBulkAssignView.as_view(), name="admin-bulk-assign-shift"),
    path("admin/shift/configure/", AdminShiftConfigurationView.as_view(), name="admin-shift-configure"),
    path("admin/shift/all/", AdminAllShiftsView.as_view(), name="admin-shifts-all"),
]
