# Generated by Django 5.2.6 on 2026-09-22 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_employee_must_change_password_employee_section_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("is_paid", models.BooleanField(default=True)),
                ("requires_document", models.BooleanField(default=False)),
                ("allow_half_day", models.BooleanField(default=True)),
                ("allow_past_dates", models.BooleanField(default=True)),
                ("allow_future_dates", models.BooleanField(default=True)),
                ("min_notice_days", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("FULL_DAY", "Full Day"),
                            ("FIRST_HALF", "First Half"),
                            ("SECOND_HALF", "Second Half"),
                        ],
                        default="FULL_DAY",
                        max_length=20,
                    ),
                ),
                ("duration_days", models.DecimalField(decimal_places=1, max_digits=5)),
                ("reason", models.TextField()),
                ("attachment", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_remarks", models.TextField(blank=True, default="")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="employees.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="leave_management.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("CONTRACT", "Contract"),
                            ("INTERN", "Intern"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "annual_entitlement",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                ("allow_carry_forward", models.BooleanField(default=False)),
                (
                    "max_carry_forward",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                ("unused_expires", models.BooleanField(default=True)),
                ("max_consecutive_days", models.IntegerField(default=10)),
                ("min_notice_days", models.IntegerField(default=0)),
                ("allow_half_day", models.BooleanField(default=True)),
                ("requires_document", models.BooleanField(default=False)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="leave_management.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "employee_type", "leave_type__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee_type", "leave_type", "effective_from"),
                        name="unique_policy_per_employee_type_leave_type_effective_from",
                    )
                ],
            },
        ),
    ]
