# Generated by Django 5.2.6 on 2026-09-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("leave_management", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="leave_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="leave_management.leaverequest",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("INCOMPLETE", "Incomplete"),
                    ("LEAVE", "Leave"),
                ],
                default="INCOMPLETE",
                max_length=20,
            ),
        ),
    ]
