# Generated by Django 5.2.17 on 2026-09-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_leave_request_alter_attendance_status'),
        ('employees', '0003_employee_face_template_employee_has_face_enrolled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('ENROLLMENT', 'Enrollment')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED_NO_FACE', 'Failed - No Face'), ('FAILED_MULTI_FACE', 'Failed - Multiple Faces'), ('FAILED_UNKNOWN', 'Failed - Unknown Identity'), ('FAILED_ERROR', 'Failed - Error')], max_length=20)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
