# Generated by Django 5.2.17 on 2026-09-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_check_in_accuracy_and_more'),
        ('attendance', '0003_attendanceauditlog'),
    ]

    operations = [
    ]
