# Generated by Django 5.2.17 on 2026-09-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_merge_20260924_2021'),
        ('attendance', '0005_alter_attendancecorrection_attendance'),
    ]

    operations = [
    ]
