# Generated by Django 5.2.17 on 2026-09-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_shift_attendanceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='employment_type',
            field=models.CharField(
                blank=True,
                choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')],
                default='',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['employment_type', 'is_active'], name='attendance_s_employm_idx'),
        ),
    ]
