# Generated by Django 5.2.6 on 2026-09-27 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_add_employment_type_to_shift"),
        ("employees", "0006_employee_shift"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("FORGOT_CHECK_IN", "Forgot Check-In"),
                            ("FORGOT_CHECK_OUT", "Forgot Check-Out"),
                            ("INCORRECT_ATTENDANCE", "Incorrect Attendance"),
                            ("SYSTEM_ISSUE", "System Issue"),
                        ],
                        max_length=30,
                    ),
                ),
                ("existing_check_in", models.DateTimeField(blank=True, null=True)),
                ("existing_check_out", models.DateTimeField(blank=True, null=True)),
                ("requested_check_in", models.DateTimeField(blank=True, null=True)),
                ("requested_check_out", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="shift",
            new_name="attendance__employm_5cd721_idx",
            old_name="attendance_s_employm_idx",
        ),
        migrations.AddField(
            model_name="regularizationrequest",
            name="attendance_correction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="regularization_request",
                to="attendance.attendancecorrection",
            ),
        ),
        migrations.AddField(
            model_name="regularizationrequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regularization_requests",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="regularizationrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="regularization_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="regularizationrequest",
            index=models.Index(
                fields=["employee", "status"], name="attendance__employe_1ca243_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regularizationrequest",
            index=models.Index(
                fields=["status", "created_at"], name="attendance__status_caf8cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regularizationrequest",
            index=models.Index(
                fields=["attendance_date"], name="attendance__attenda_23d5ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regularizationrequest",
            index=models.Index(
                fields=["reviewed_by", "reviewed_at"],
                name="attendance__reviewe_4c4df5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="regularizationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("employee", "attendance_date", "status"),
                name="unique_pending_regularization_per_employee_per_date",
            ),
        ),
    ]
