# Generated by Django 5.2.6 on 2026-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_regularizationrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularizationrequest",
            name="approved_check_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="regularizationrequest",
            name="approved_check_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
