# Generated by Django 5.2.17 on 2026-09-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_officelocation'),
        ('attendance', '0009_regularizationrequest_and_more'),
    ]

    operations = [
    ]
