# Generated by Django 5.2.6 on 2026-09-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_regularizationrequest_approved_check_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularizationrequest",
            name="attachment",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="regularizationrequest",
            name="period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="regularizationrequest",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="regularizationrequest",
            name="period_type",
            field=models.CharField(
                choices=[("DAY", "Day"), ("WEEK", "Week"), ("MONTH", "Month")],
                default="DAY",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RegularizationRequestDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("FORGOT_CHECK_IN", "Forgot Check-In"),
                            ("FORGOT_CHECK_OUT", "Forgot Check-Out"),
                            ("INCORRECT_ATTENDANCE", "Incorrect Attendance"),
                            ("SYSTEM_ISSUE", "System Issue"),
                        ],
                        max_length=30,
                    ),
                ),
                ("existing_check_in", models.DateTimeField(blank=True, null=True)),
                ("existing_check_out", models.DateTimeField(blank=True, null=True)),
                ("requested_check_in", models.DateTimeField(blank=True, null=True)),
                ("requested_check_out", models.DateTimeField(blank=True, null=True)),
                ("approved_check_in", models.DateTimeField(blank=True, null=True)),
                ("approved_check_out", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("description", models.TextField(blank=True, default="")),
                (
                    "attendance_correction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regularization_request_days",
                        to="attendance.attendancecorrection",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="attendance.regularizationrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["attendance_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request", "attendance_date"),
                        name="unique_regularization_request_day",
                    )
                ],
            },
        ),
    ]
