# Generated by Django 5.2.6 on 2026-09-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_regularization_quota_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("INCOMPLETE", "Incomplete"),
                    ("ABSENT", "Absent"),
                    ("LEAVE", "Leave"),
                ],
                default="INCOMPLETE",
                max_length=20,
            ),
        ),
    ]
