# Generated by Django 5.2.6 on 2026-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="section",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="employee",
            name="subsection",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
