# Generated by Django 5.2.17 on 2026-09-23 19:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_must_change_password_employee_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_template',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=512),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_face_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
