# Generated by Django 5.2.17 on 2026-09-29 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('category', models.CharField(max_length=32)),
                ('event_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DENIED', 'Denied'), ('PENDING', 'Pending'), ('RETRY', 'Retry'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], max_length=10)),
                ('actor_role', models.CharField(max_length=20)),
                ('target_type', models.CharField(blank=True, default='', max_length=128)),
                ('target_id', models.CharField(blank=True, default='', max_length=128)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['timestamp', 'id'], name='system_log_time_idx'), models.Index(fields=['event_type', 'timestamp', 'id'], name='system_log_event_idx'), models.Index(fields=['category', 'timestamp', 'id'], name='system_log_category_idx'), models.Index(fields=['severity', 'timestamp', 'id'], name='system_log_severity_idx'), models.Index(fields=['status', 'timestamp', 'id'], name='system_log_status_idx'), models.Index(fields=['actor', 'timestamp', 'id'], name='system_log_actor_idx'), models.Index(fields=['request_id'], name='system_log_request_idx'), models.Index(fields=['target_type', 'target_id', 'timestamp'], name='system_log_target_idx')],
            },
        ),
    ]
